create table client(
	cid VARCHAR(45) NOT NULL,
	pass VARCHAR(45) NOT NULL,
	fname VARCHAR(45) NOT NULL,
	lname VARCHAR(45) NOT NULL,
	balance VARCHAR(45) DEFAULT 0, 
	PRIMARY KEY(cid)
);

create table orders(
	oid VARCHAR(45) NOT NULL,
	cid VARCHAR(45) NOT NULL,
	total_price VARCHAR(45) NOT NULL,
	PRIMARY KEY (oid),
	FOREIGN KEY (cid) REFERENCES client(cid)
	ON UPDATE CASCADE 	ON DELETE CASCADE
);

CREATE TABLE item(
	itemid VARCHAR(45) NOT NULL,
	iname VARCHAR(45) NOT NULL,
	price VARCHAR(45) NOT NULL,
	qty VARCHAR(45) NOT NULL,
	category VARCHAR(45) NOT NULL,
	PRIMARY KEY(itemid)
);

CREATE TABLE purchased_items (
	cid VARCHAR(45) NOT NULL,
	oid VARCHAR(45) NOT NULL,
	itemid VARCHAR(45) NOT NULL,
	PRIMARY KEY(cid,oid,itemid),
	FOREIGN KEY (cid)
	ON UPDATE CASCADE 	ON DELETE CASCADE,
	FOREIGN KEY (oid)
	ON UPDATE CASCADE 	ON DELETE CASCADE,
	FOREIGN KEY (itemid)
	ON UPDATE CASCADE 	ON DELETE CASCADE,
);
